### ISSUE TITLE
testing of the results of the training

### ISSUE THREAD

**Issue by ZKCCZ** [krennic999/MPI#1]
I followed your configuration exactly, and when I read my own trained net_g_latest.pth after training, it comes up with ‘Unexpected key(s) in state_dict: "net.1.0.1.1.weight." 
But when I read the pre-trained model you provided, his keys are exactly the same as the .pth I trained myself.

**Comment by ZKCCZ** [comment]
fixed needed to rename the model end with 'skip' which is similr to the name of the pretrained model

**Comment by krennic999** [comment]
The network architecture specified in our code is recognized by the name of checkpoints, follow our provided example.
Thanks very much for replicating our work! If any else problem exists or any other help needed, please inform us at xiao_xiao@mail.ustc.edu.cn!
